server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule_db?useUnicode=yes&characterEncoding=UTF-8&connectionCollation=utf8_general_ci
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl